# 역할: 거래 심볼, 시간봉, 기본 설정값을 정의하는 파일.
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = BASE_DIR / "data"
MODEL_DIR = BASE_DIR / "models"
DB_PATH = DATA_DIR / "trading.db"

SYMBOL = "BTCUSDT"
PRODUCT_TYPE = "USDT-FUTURES"

# 분석 대상 시간봉: 전략 판단은 1m/5m를 우선 사용하고, 나머지는 화면 표시와 추세 확인용으로 유지합니다.
TIMEFRAMES = ["1m", "5m", "15m", "30m", "1H", "4H", "6H", "1D"]
DEFAULT_TIMEFRAME = "1m"
TIMEFRAME = DEFAULT_TIMEFRAME

# MA200/RSI/ATR/거래량 지표 안정화를 위해 최근 660개 확정 캔들을 유지합니다.
CANDLE_ANALYSIS_LIMIT = 660
RECENT_CANDLE_LIMIT_BY_TIMEFRAME = {tf: CANDLE_ANALYSIS_LIMIT for tf in TIMEFRAMES}
RECENT_CANDLE_LIMIT = RECENT_CANDLE_LIMIT_BY_TIMEFRAME[DEFAULT_TIMEFRAME]

BITGET_REST_BASE = "https://api.bitget.com"
BITGET_WS_PUBLIC = "wss://ws.bitget.com/v2/ws/public"
USE_DEMO_DATA = False
API_TIMEOUT_SECONDS = 8
REFRESH_INTERVAL_MS = 15000
INITIAL_CANDLE_LIMIT = CANDLE_ANALYSIS_LIMIT
REFRESH_CANDLE_LIMIT = 2

# Futures execution model
SPREAD_NORMAL_RATE = 0.0003
SPREAD_CAUTION_RATE = 0.0007
TAKER_FEE_RATE = 0.0006
MAKER_FEE_RATE = 0.0003
FUNDING_NORMAL_RATE = 0.0001
FUNDING_CAUTION_RATE = 0.0003
FUNDING_BLOCK_RATE = 0.0005
